name: Backend tests
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: ./backend/functions
        run: npm i
      - name: Run tests
        working-directory: ./backend/functions
        run: |
          npm run serve &
          sleep 30
          npm test