name: Backend tests
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install packages
        working-directory: ./backend/functions
        run: npm i
      - name: Run setup
        working-directory: ./backend/functions
        run: |
          npm install -g firebase-tools
          npm run setup
          cat /home/runner/.npm/_logs/*-debug.log
      - name: Run tests
        working-directory: ./backend/functions
        run: |
          npm run serve &
          sleep 60
          npm test