name: Frontend style checking
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lints frontend code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn
      - name: Lint
        run: yarn lint